version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: mvn clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    after:
      upstream: rm -rf ./*

build:
  - project: kiegroup/kie-jpmml-integration
    skip: true